# Generated by Django 5.1.3 on 2024-11-26 06:52

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                ("max_group_size", models.PositiveIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("difficult", "Difficult"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("rating_qty", models.PositiveIntegerField(default=0)),
                ("price", models.PositiveIntegerField()),
                ("price_discount_percent", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StartDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_dates",
                        to="tours.tour",
                    ),
                ),
            ],
        ),
    ]
