# Generated by Django 5.1.3 on 2024-11-26 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Duration must be at least 1 day."
                    ),
                    django.core.validators.MaxValueValidator(
                        30, message="Duration must be at least 30 days."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="max_group_size",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Max group size must be at least 1 person."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Max group size must be max 100 people."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="price_discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="Price discount percentage must be at least 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        100.0,
                        message="Price discount percentage must be max 100 people.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="Rating must be at least 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        5.0, message="Rating must be max 5."
                    ),
                ],
            ),
        ),
    ]
